let selected = null; let versions = []; let logs = '';
const $ = s => document.querySelector(s); const $$ = s => document.querySelectorAll(s);
function toast(message) { $('#toast').textContent = message; $('#toast').classList.add('show'); setTimeout(() => $('#toast').classList.remove('show'), 3500); }
function show(view) { ['welcome','create-view','server-view'].forEach(id => $(`#${id}`).hidden = id !== view); }
async function refresh() { const root = await window.api.getRoot(); $('#root-path').textContent = root || 'No folder selected'; const servers = await window.api.listServers(); $('#server-list').innerHTML = servers.map(s => `<button class="server-item ${selected?.id===s.id?'selected':''}" data-id="${s.id}">${escapeHtml(s.name)}<small>${s.type} · ${s.version}</small></button>`).join(''); $$('.server-item').forEach(b => b.onclick = () => selectServer(servers.find(s => s.id === b.dataset.id))); if (!root) show('welcome'); else if (!selected) show('welcome'); }
function escapeHtml(s) { const e=document.createElement('span');e.textContent=s;return e.innerHTML; }
async function chooseRoot() { const root = await window.api.chooseRoot(); if (root) { selected = null; await refresh(); show('create-view'); } }
async function selectServer(server) { selected = server; logs = ''; $('#logs').textContent = 'Server is not running.'; $('#server-name').textContent = server.name; $('#server-kind').textContent = server.type.toUpperCase(); $('#server-version').textContent = `Minecraft ${server.version}${server.build ? ` · Paper build ${server.build}` : ''}`; $('#server-location').textContent = `${await window.api.getRoot()}\\${server.id}`; $('#properties').value = await window.api.properties(server.id); await refreshMods(); await refresh(); show('server-view'); }
async function refreshMods() { if (!selected) return; const mods = await window.api.mods(selected.id); $('#mod-list').innerHTML = mods.length ? mods.map(m => `<li>${escapeHtml(m)}</li>`).join('') : '<li class="muted">No mods installed yet.</li>'; }
async function loadVersions() { try { versions = await window.api.listVersions(); $('#version').innerHTML = versions.map(v => `<option value="${v}">${v}</option>`).join(''); await forgeVersions(); } catch (e) { toast(`Could not load versions: ${e.message}`); } }
const typeHelp = {vanilla:'The official Mojang server, clean and unmodified.',paper:'Fast and reliable server software with broad plugin compatibility.',fabric:'A lightweight modding platform. Add Fabric mods from the Mods tab.',forge:'A classic modding platform. The official Forge installer runs locally.'};
async function forgeVersions() { if ($('#type').value !== 'forge') return; $('#forge-version').innerHTML = '<option>Loading Forge builds…</option>'; try { const builds = await window.api.listForge($('#version').value); $('#forge-version').innerHTML = builds.length ? builds.map(v => `<option value="${v}">${v}</option>`).join('') : '<option>No Forge builds found</option>'; } catch { $('#forge-version').innerHTML = '<option>Could not load Forge builds</option>'; } }
$('#choose-root').onclick = chooseRoot; $('#welcome-root').onclick = chooseRoot; $('#new-server').onclick = () => { if ($('#root-path').textContent === 'No folder selected') chooseRoot(); else show('create-view'); }; $$('.close-create').forEach(b => b.onclick = () => selected ? show('server-view') : show('welcome'));
$('#type').onchange = () => { const forge = $('#type').value === 'forge'; $('#forge-field').hidden = !forge; $('#type-help').textContent = typeHelp[$('#type').value]; if (forge) forgeVersions(); }; $('#version').onchange = forgeVersions;
$('#create-form').onsubmit = async e => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.target)); const button = e.submitter; button.disabled = true; button.textContent = 'Creating…'; try { const server = await window.api.create(data); toast('Server created. Accept the EULA, then start it.'); await selectServer(server); } catch (err) { toast(err.message); } finally { button.disabled = false; button.textContent = 'Download & create server'; } };
$$('.tabs button').forEach(button => button.onclick = () => { $$('.tabs button').forEach(b => b.classList.toggle('active', b===button)); $$('.tab').forEach(tab => tab.hidden = tab.id !== `tab-${button.dataset.tab}`); });
$('#save-properties').onclick = async () => { await window.api.saveProperties(selected.id, $('#properties').value); toast('Properties saved.'); }; $('#eula').onclick = async () => { await window.api.setEula(selected.id, true); toast('EULA accepted.'); }; $('#add-mod').onclick = async () => { await window.api.addMod(selected.id); await refreshMods(); }; $('#start').onclick = async () => { await window.api.start(selected.id); $('#start').disabled = true; $('#stop').disabled = false; $('#status').textContent = 'RUNNING'; $('#status').classList.add('running'); logs=''; $('#logs').textContent='Starting server…\n'; }; $('#stop').onclick = () => window.api.stop(selected.id);
window.api.onLog((id, text) => { if (selected?.id !== id) return; logs += text; $('#logs').textContent = logs; $('#logs').scrollTop = $('#logs').scrollHeight; }); window.api.onStopped((id, code) => { if (selected?.id !== id) return; $('#start').disabled=false; $('#stop').disabled=true; $('#status').textContent='OFFLINE'; $('#status').classList.remove('running'); logs += `\nServer stopped (code ${code}).`; $('#logs').textContent=logs; });
refresh(); loadVersions();
