import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const descriptions: Record<ServerType, string> = { vanilla: 'The official Mojang server, clean and unmodified.', paper: 'Fast, reliable server software with plugin compatibility.', fabric: 'A lightweight modding platform. Add Fabric mods from the Mods tab.', forge: 'A classic modding platform. The official installer runs locally.' };
function App() {
  const [root, setRoot] = useState(''); const [servers, setServers] = useState<Server[]>([]); const [selected, setSelected] = useState<Server | null>(null); const [view, setView] = useState<'welcome' | 'create' | 'server'>('welcome'); const [versions, setVersions] = useState<string[]>([]); const [type, setType] = useState<ServerType>('vanilla'); const [version, setVersion] = useState(''); const [forge, setForge] = useState<string[]>([]); const [properties, setProperties] = useState(''); const [mods, setMods] = useState<string[]>([]); const [tab, setTab] = useState('overview'); const [running, setRunning] = useState(false); const [logs, setLogs] = useState('Server is not running.'); const [toast, setToast] = useState('');
  const notify = (text: string) => { setToast(text); setTimeout(() => setToast(''), 3500); };
  const reload = async () => { const [serverRoot, found] = await Promise.all([window.blocksmith.getRoot(), window.blocksmith.listServers()]); setRoot(serverRoot); setServers(found); };
  useEffect(() => { reload(); window.blocksmith.listVersions().then(list => { setVersions(list); setVersion(list[0] || ''); }).catch(e => notify(`Could not load versions: ${e.message}`)); window.blocksmith.onLog((id, text) => { if (selected?.id === id) setLogs(previous => previous + text); }); window.blocksmith.onStopped((id, code) => { if (selected?.id === id) { setRunning(false); setLogs(previous => `${previous}\nServer stopped (code ${code}).`); } }); }, [selected?.id]);
  useEffect(() => { if (type === 'forge' && version) window.blocksmith.listForge(version).then(setForge).catch(() => setForge([])); }, [type, version]);
  const chooseRoot = async () => { const selectedRoot = await window.blocksmith.chooseRoot(); if (selectedRoot) { await reload(); setView('create'); } };
  const chooseServer = async (server: Server) => { setSelected(server); setProperties(await window.blocksmith.properties(server.id)); setMods(await window.blocksmith.mods(server.id)); setLogs('Server is not running.'); setRunning(false); setView('server'); setTab('overview'); };
  const create = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); try { const server = await window.blocksmith.create({ name: String(data.get('name')), type, version, forgeVersion: String(data.get('forgeVersion') || '') }); notify('Server created. Accept the EULA, then start it.'); await reload(); await chooseServer(server); } catch (e) { notify(e instanceof Error ? e.message : 'Server creation failed.'); } };
  return <><aside><div className="brand">BLOCK<span>SMITH</span></div><p className="tagline">Local Minecraft server manager</p><button className="outline" onClick={chooseRoot}>Choose server folder</button><p className="path">{root || 'No folder selected'}</p><div className="side-label">YOUR SERVERS</div><nav>{servers.map(server => <button key={server.id} className={`server-item ${selected?.id === server.id ? 'selected' : ''}`} onClick={() => chooseServer(server)}>{server.name}<small>{server.type} · {server.version}</small></button>)}</nav><button className="new" onClick={() => root ? setView('create') : chooseRoot()}>＋ Create server</button></aside><main>
    {view === 'welcome' && <section className="empty"><div className="pickaxe">◆</div><h1>Your servers, in one place.</h1><p>Choose a folder to start creating and managing local Minecraft servers.</p><button onClick={chooseRoot}>Choose server folder</button></section>}
    {view === 'create' && <section><div className="top"><div><p className="eyebrow">NEW INSTANCE</p><h1>Create a server</h1></div><button className="outline" onClick={() => setView(selected ? 'server' : 'welcome')}>Cancel</button></div><form className="card form" onSubmit={create}><label>Server name<input name="name" placeholder="Weekend world" required maxLength={64}/></label><div className="twocol"><label>Server software<select value={type} onChange={e => setType(e.target.value as ServerType)}><option value="vanilla">Vanilla</option><option value="paper">Paper — optimized plugins</option><option value="fabric">Fabric — lightweight mods</option><option value="forge">Forge — modpacks</option></select></label><label>Minecraft version<select value={version} onChange={e => setVersion(e.target.value)}>{versions.map(item => <option key={item}>{item}</option>)}</select></label></div>{type === 'forge' && <label>Forge build<select name="forgeVersion">{forge.map(build => <option key={build}>{build}</option>)}</select></label>}<p className="hint">{descriptions[type]}</p><button className="primary">Download & create server</button></form></section>}
    {view === 'server' && selected && <section><div className="top"><div><p className="eyebrow">{selected.type.toUpperCase()}</p><h1>{selected.name}</h1><p className="muted">Minecraft {selected.version}{selected.build ? ` · Paper build ${selected.build}` : ''}</p></div><div className="actions"><span className={`status ${running ? 'running' : ''}`}>{running ? 'RUNNING' : 'OFFLINE'}</span><button className="primary" disabled={running} onClick={async () => { await window.blocksmith.start(selected.id); setRunning(true); setLogs('Starting server…\n'); }}>Start server</button><button className="danger" disabled={!running} onClick={() => window.blocksmith.stop(selected.id)}>Stop</button></div></div><div className="tabs">{['overview', 'properties', 'mods', 'console'].map(item => <button key={item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{item === 'properties' ? 'server.properties' : item[0].toUpperCase() + item.slice(1)}</button>)}</div>
      {tab === 'overview' && <div className="card overview"><h2>Before first launch</h2><p>By starting the server, you confirm you agree to the <a href="https://aka.ms/MinecraftEULA">Minecraft EULA</a>.</p><button className="outline" onClick={async () => { await window.blocksmith.setEula(selected.id, true); notify('EULA accepted.'); }}>Accept EULA</button><h2>Server location</h2><code>{root}\{selected.id}</code></div>}
      {tab === 'properties' && <div className="card"><div className="tabtitle"><div><h2>Server properties</h2><p>Edit Minecraft’s native configuration file directly.</p></div><button className="primary" onClick={async () => { await window.blocksmith.saveProperties(selected.id, properties); notify('Properties saved.'); }}>Save changes</button></div><textarea value={properties} spellCheck={false} onChange={e => setProperties(e.target.value)}/></div>}
      {tab === 'mods' && <div className="card"><div className="tabtitle"><div><h2>Installed mods</h2><p>Works with Fabric and Forge. Add `.jar` files from your computer.</p></div><button className="primary" onClick={async () => { await window.blocksmith.addMod(selected.id); setMods(await window.blocksmith.mods(selected.id)); }}>Add mod files</button></div><ul className="modlist">{mods.length ? mods.map(mod => <li key={mod}>{mod}</li>) : <li className="muted">No mods installed yet.</li>}</ul></div>}
      {tab === 'console' && <div className="card console"><div className="tabtitle"><div><h2>Live console</h2><p>Output from the running server.</p></div></div><pre>{logs}</pre></div>}</section>}
  </main><div id="toast" className={toast ? 'show' : ''}>{toast}</div></>;
}
createRoot(document.getElementById('root')!).render(<App/>);
